services:
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8095:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel
    command: >
      sh -c "
      echo 'server {
          listen 80;
          server_name localhost;
          root /var/www/html/public;
          index index.php index.html;

          location / {
              try_files \$$uri \$$uri/ /index.php?\$$query_string;
          }

          location ~ \.php$$ {
              fastcgi_pass app:9000;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME \$$document_root\$$fastcgi_script_name;
              include fastcgi_params;
          }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - laravel
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ERP-system
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel
  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel

volumes:
  postgres_data:
  redis_data:

networks:
  laravel:
    driver: bridge